[package]
name = "quilt"
version = "0.1.0"
edition = "2021"
authors = ["Monday Romelfanger"]
description = "A local-first, modular memory and context engine"

[[bin]]
name = "quilt"
path = "src/main.rs"

[dependencies]
# Core dependencies
cuid2 = "0.1.2"
time = { version = "0.3", features = ["serde", "macros"] }
walkdir = "2.4.0"
thiserror = "1.0.57"
tokio = { version = "1.44.2", features = ["macros", "rt", "rt-multi-thread", "sync"] }

[dev-dependencies]
tempfile = "3.10.1"  # For creating temporary test directories

# We'll add more dependencies as we implement features 