[package]
name = "quilt"
version = "0.1.0"
edition = "2021"
authors = ["Monday Romelfanger"]
description = "A local-first, modular memory and context engine"

[dependencies]
# Core dependencies
cuid2 = "0.1.2"
time = { version = "0.3", features = ["serde", "macros"] }
event-emitter = "0.1.1"

# We'll add more dependencies as we implement features 