[package]
name = "sidecar"
version = "0.1.0"
edition = "2021"
authors = ["Monday Romelfanger"]
description = "A local-first, modular memory and context server"

[dependencies]
# We'll add dependencies as we implement features 