# Configuration for rustfmt
# Only using options available in stable Rust

edition = "2021"
max_width = 100
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
match_block_trailing_comma = false
match_arm_leading_pipes = "Never"
merge_derives = true
use_field_init_shorthand = false
use_try_shorthand = false 