edition = "2021"
max_width = 100
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"
imports_indent = "Block"
imports_layout = "Mixed"
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true
reorder_impl_items = true
type_punctuation_density = "Wide"
space_before_colon = false
space_after_colon = true
spaces_around_ranges = false
binop_separator = "Front"
remove_nested_parens = true
combine_control_expr = true
overflow_delimited_expr = false
struct_field_align_threshold = 0
enum_discrim_align_threshold = 0
match_arm_blocks = true
match_block_trailing_comma = false
trailing_semicolon = true
trailing_comma = "Vertical"
match_arm_leading_pipes = "Never"
force_multiline_blocks = false
format_macro_matchers = false
format_macro_bodies = true
format_strings = false
format_code_in_doc_comments = false
doc_comment_code_block_width = 100
error_on_line_overflow = false
error_on_unformatted = false
normalize_comments = false
normalize_doc_attributes = false
license_template_path = ""
merge_derives = true
use_field_init_shorthand = false
use_try_shorthand = false
merge_imports = false 