[book]
authors = ["Monday Romelfanger"]
language = "en"
multilingual = false
src = "src"
title = "Sidecar Documentation"
description = "Documentation for Sidecar - A local-first, modular memory and context server"

[output.html]
git-repository-url = "https://github.com/pandallel/sidecar"
edit-url-template = "https://github.com/pandallel/sidecar/edit/main/docs/src/{path}"

[preprocessor.admonish]
command = "mdbook-admonish"
renderer = ["html"]
