name: Automatic AI Code Review

on:
  pull_request:
    types: [opened]

permissions: write-all

jobs:
  review:
    # Skip this job if the PR author is dependabot
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: AI Code Reviewer
        uses: villesau/ai-codereviewer@v2.7.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_MODEL: "gpt-4o-mini" # Optional: defaults to "gpt-4"
          exclude: "**/*.json, Cargo.lock" # Exclude patterns for files that don't need review
